# Generated by Django 4.2.29 on 2026-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sociallink_is_active_alter_sociallink_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated technologies (e.g. Django, React, Python)', max_length=500),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='Geeta R Galagali', max_length=200),
        ),
    ]
