# Generated by Django 4.2.29 on 2026-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_technologies_alter_herosection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your professional PDF resume', null=True, upload_to='resumes/'),
        ),
    ]
